name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Navegando até o diretório ToDoListVite, instalando o npm e rodando o código
        run: | 
          cd ToDoListVite
          npm ci
          npm run build

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Navegando até o diretório ToDoListVite para rodar testes Cypress
  #       run: |
  #         cd ToDoListVite
  #         npm ci
  #         # Aqui você pode rodar seus testes Cypress
  #         # Substitua o comando abaixo pelo comando real para rodar seus testes
  #         npm run cypress:run
