name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Navegando até o diretório ToDoListVite, instalando o npm e rodando o código
        run: | 
          cd ToDoListVite
          npm ci
          npm install serve --save-dev
          npm run start

      - name: Navegando até o diretório ToDoListVite para rodar testes Cypress
        run: |
          cd Cypress
          npm ci
          ./node_modules/.bin/cypress run

