name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Navegando até o diretório ToDoListVite, instalando o npm e rodando o código
        run: | 
          cd ToDoListVite
          npm ci
          npm run build

      - name: Salvando build como artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ToDoListVite/build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Baixando build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ToDoListVite/build

      - name: Navegando até o diretório ToDoListVite para rodar testes Cypress
        run: |
          cd Cypress
          npm ci
          ./node_modules/.bin/cypress run
